## global
seed: 31
device: cuda
debug: False 
running_mode: train #  train test finetune

epochs: 100
lr_init: 0.0005
batch_size: 64

num_nodes : 50

## train
load_train_model: False
train_best_path: None
use_pretrain: True
best_path: None   # for testing dataset.
early_stop_patience: 5
hidden_dim: 32
num_heads: 8


## dataset
dataset: cdata
datapath: cdata.npy
scalar_type: Standard
train_ratio:  0.7
valid_ratio: 0.2
test_ratio: 0.1
adj_mx: dist_mx.npy
od_mx: od_mx.npy




