## global
seed: 31
device: cuda
debug: False 
running_mode: train #  train test finetune

## train
num_hist: 12
num_pred: 12
early_stop_patience: 5
epochs: 100
lr_init: 0.001
load_model: False
best_path: logs\udata\20240320-114934\best_model.pth   # for testing dataset.
grad_norm: True
max_grad_norm: 8

## model
hidden_dim: 16
num_heads: 8
batch_size: 64
block_layers: 1
input_dim: 3
output_dim: 2

## dataset
dataset: udata
scalar_type: Standard
train_ratio:  0.7
valid_ratio: 0.2
test_ratio: 0.1
cheb_order: 3
