## global
seed: 31
device: cuda
debug: False 
running_mode: train #  train test finetune

## train
num_hist: 12
num_pred: 12
early_stop_patience: 10
epochs: 100
lr_init: 0.001
load_model: False
best_path: None   # for testing dataset.

## model
hidden_dim: 16
num_heads: 8
batch_size: 64
block_layers: 2
input_dim: 3
output_dim: 2

## dataset
dataset: udata
scalar_type: Standard
train_ratio:  0.7
valid_ratio: 0.2
test_ratio: 0.1


# ## data 
# data_dir: data
# dataset: udata  
# input_length: 19 # 4+5*3
# batch_size: 32
# test_batch_size: 32
# graph_file: data/udata/od.npy
# adj_file: data/udata/adj.npy
# num_hist: 12
# num_pred: 1

# ## model 
# d_input: 3                  # means inflow and outflow
# d_output: 2                 # means inflow and outflow
# d_model: 16
# heads: 8
# dropout: 0.2
# percent: 0.1                # augumentation percentage  
# shm_temp: 0.5               # temperature for loss of spatial heterogeneity modeling  , 0.5 is best for NYCBike
# nmb_prototype: 6            # number of cluster 
# yita: 0.6                   # balance for inflow loss and outflow loss, $yita * inflow + (1 - yita) * outflow$

# ## train
# epochs: 100
# lr_init: 0.001
# early_stop: True
# early_stop_patience: 15
# grad_norm: True
# max_grad_norm: 5
# use_dwa: True         # whether to use dwa for loss balance
# temp: 4               # tempurature parameter in dwa, a larger T means more similer weights
